// Impossible to find import for now
import { Translations } from "@aws-amplify/ui-components"

// See official Amplify UI labels: https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/common/Translations.ts
export const strings = {
    en: {
        signInHeader: "Sign in your Fizz account",
        signUpHeader: "Create your Fizz account",
        resetPasswordHeader: 'Reset your password',
        confirmSignUpHeader: 'Confirm Sign up',
        emailLabel: "Email",
        emailPlaceHolder: "your.email@example.com",
        passwordLabel: "Password",
        passwordPlaceHolder: "xxxxxxxxx",
        signInButtonText: "SIGN IN",
        [Translations.SEND_CODE]: 'Send Code!!!', // Customize default English text by customizing English translation  https://github.com/aws-amplify/amplify-js/pull/4979#discussion_r384834093
    },
    fr: {
        signInHeader: "Sign in your Fizz account FR",
        signUpHeader: "Create your Fizz account FR",
        resetPasswordHeader: 'Reset your password FR',
        confirmSignUpHeader: 'Confirm Sign up FR',
        emailLabel: "Email FR",
        emailPlaceHolder: "your.email@example.com FR",
        passwordLabel: "Password FR",
        passwordPlaceHolder: "xxxxxxxxx",
        signInButtonText: "SIGN IN FR",
        [Translations.FORGOT_PASSWORD_TEXT]: 'Forgot your password? FR',
        [Translations.RESET_PASSWORD_TEXT]: 'Reset password FR',
        [Translations.NO_ACCOUNT_TEXT]: "No account? FR ",
        [Translations.CREATE_ACCOUNT_TEXT]: "Create account FR",
        [Translations.SIGN_IN_ACTION]: 'Sign In FR',
        [Translations.EMAIL_LABEL]: 'Email Address * FR',
        [Translations.SIGN_UP_EMAIL_PLACEHOLDER]: 'Email FR',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? FR',
        [Translations.PASSWORD_LABEL]: 'Password * FR',
        [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: 'Password FR',
        [Translations.PHONE_LABEL]: 'Phone Number * FR',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? FR',
        [Translations.SIGN_IN_TEXT]: 'Sign in FR',
        [Translations.SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Create Account FR',
        [Translations.BACK_TO_SIGN_IN]: 'Back to Sign In FR',
        [Translations.SEND_CODE]: 'Send Code!!! FR',
        [Translations.CONFIRM_SIGN_UP_CODE_LABEL]: 'Confirmation Code FR',
        [Translations.CONFIRM_SIGN_UP_CODE_PLACEHOLDER]: 'Enter your code FR',
        [Translations.CONFIRM_SIGN_UP_LOST_CODE]: 'Lost your code? FR',
        [Translations.CONFIRM_SIGN_UP_RESEND_CODE]: 'Resend Code FR',
        [Translations.CONFIRM_SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Confirm FR',
        [Translations.CODE_PLACEHOLDER]: 'Enter code FR',
        [Translations.CODE_LABEL]: 'Verification code FR',
    },
    es: {
        signInHeader: "Sign in your Fizz account ES",
        signUpHeader: "Create your Fizz account ES",
        resetPasswordHeader: 'Reset your password ES',
        confirmSignUpHeader: 'Confirm Sign up ES',
        emailLabel: "Email ES",
        emailPlaceHolder: "your.email@example.com ES",
        passwordLabel: "Password ES",
        passwordPlaceHolder: "xxxxxxxxx",
        signInButtonText: "SIGN IN ES",
        [Translations.FORGOT_PASSWORD_TEXT]: 'Forgot your password? ES',
        [Translations.RESET_PASSWORD_TEXT]: 'Reset password ES',
        [Translations.NO_ACCOUNT_TEXT]: "No account? ES ",
        [Translations.CREATE_ACCOUNT_TEXT]: "Create account ES",
        [Translations.SIGN_IN_ACTION]: 'Sign In ES',
        [Translations.EMAIL_LABEL]: 'Email Address * ES',
        [Translations.SIGN_UP_EMAIL_PLACEHOLDER]: 'Email ES',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? ES',
        [Translations.PASSWORD_LABEL]: 'Password * ES',
        [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: 'Password ES',
        [Translations.PHONE_LABEL]: 'Phone Number * ES',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? ES',
        [Translations.SIGN_IN_TEXT]: 'Sign in ES',
        [Translations.SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Create Account ES',
        [Translations.BACK_TO_SIGN_IN]: 'Back to Sign In ES',
        [Translations.SEND_CODE]: 'Send Code!!! ES',
        [Translations.CONFIRM_SIGN_UP_CODE_LABEL]: 'Confirmation Code ES',
        [Translations.CONFIRM_SIGN_UP_CODE_PLACEHOLDER]: 'Enter your code ES',
        [Translations.CONFIRM_SIGN_UP_LOST_CODE]: 'Lost your code? ES',
        [Translations.CONFIRM_SIGN_UP_RESEND_CODE]: 'Resend Code ES',
        [Translations.CONFIRM_SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Confirm ES',
        [Translations.CODE_PLACEHOLDER]: 'Enter code ES',
        [Translations.CODE_LABEL]: 'Verification code ES',
    },
    pt: {
        signInHeader: "Sign in your Fizz account PT",
        signUpHeader: "Create your Fizz account PT",
        resetPasswordHeader: 'Reset your password PT',
        confirmSignUpHeader: 'Confirm Sign up PT',
        emailLabel: "Email PT",
        emailPlaceHolder: "your.email@example.com PT",
        passwordLabel: "Password PT",
        passwordPlaceHolder: "xxxxxxxxx",
        signInButtonText: "SIGN IN PT",
        [Translations.FORGOT_PASSWORD_TEXT]: 'Forgot your password? PT',
        [Translations.RESET_PASSWORD_TEXT]: 'Reset password PT',
        [Translations.NO_ACCOUNT_TEXT]: "No account? PT ",
        [Translations.CREATE_ACCOUNT_TEXT]: "Create account PT",
        [Translations.SIGN_IN_ACTION]: 'Sign In PT',
        [Translations.EMAIL_LABEL]: 'Email Address * PT',
        [Translations.SIGN_UP_EMAIL_PLACEHOLDER]: 'Email PT',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? PT',
        [Translations.PASSWORD_LABEL]: 'Password * PT',
        [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: 'Password PT',
        [Translations.PHONE_LABEL]: 'Phone Number * PT',
        [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'Have an account? PT',
        [Translations.SIGN_IN_TEXT]: 'Sign in PT',
        [Translations.SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Create Account PT',
        [Translations.BACK_TO_SIGN_IN]: 'Back to Sign In PT',
        [Translations.SEND_CODE]: 'Send Code!!! PT',
        [Translations.CONFIRM_SIGN_UP_CODE_LABEL]: 'Confirmation Code PT',
        [Translations.CONFIRM_SIGN_UP_CODE_PLACEHOLDER]: 'Enter your code PT',
        [Translations.CONFIRM_SIGN_UP_LOST_CODE]: 'Lost your code? PT',
        [Translations.CONFIRM_SIGN_UP_RESEND_CODE]: 'Resend Code PT',
        [Translations.CONFIRM_SIGN_UP_SUBMIT_BUTTON_TEXT]: 'Confirm PT',
        [Translations.CODE_PLACEHOLDER]: 'Enter code PT',
        [Translations.CODE_LABEL]: 'Verification code PT',
    },

};