// Impossible to find import for now
import { Translations } from "@aws-amplify/ui-components"

// See official Amplify UI labels: https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/common/Translations.ts
export const strings = {
    en: {
        [Translations.NO_ACCOUNT_TEXT]: "No account yet?",
        [Translations.CREATE_ACCOUNT_TEXT]: "Create account",
        signInHeader: "Sign in your Fizz account",
        signUpHeader: "Create your fizz account",
        emailLabel: "Email",
        emailPlaceHolder: "your.email@example.com",
        passwordLabel: "Password",
        passwordPlaceHolder: "xxxxxxxxx",
        phoneNumberLabel: "Phone Number",
        phoneNumberPlaceHolder: "555-555-5555",
        signUpButtonText: "SIGN UP",
        signInButtonText: "SIGN IN",
        signInText: "Sign In",
        haveAccountText: "Have an account?",
        resetYourPassword: "Reset your password",
        sendCode: "Send Code",
    },
    fr: {
        [Translations.NO_ACCOUNT_TEXT]: "Pas encore de compte?",
        [Translations.CREATE_ACCOUNT_TEXT]: "Créer un compte",
        signInHeader: "Connexion à votre compte Fizz",
        signUpHeader: "Créer un compte Fizz",
        emailLabel: "Adresse de messagerie",
        emailPlaceHolder: "votre.email@exemple.com",
        passwordLabel: "Mot de passe",
        passwordPlaceHolder: "xxxxxxxxx",
        phoneNumberLabel: "Numéro de téléphone",
        phoneNumberPlaceHolder: "555-555-5555",
        signUpButtonText: "CREER COMPTE",
        signInButtonText: "CONNEXION",
        signInText: "Se connecter",
        haveAccountText: "Avoir un compte?",
        resetYourPassword: "Réinitialisez votre mot de passe",
        sendCode: "Envoyer le code",
    },
    es: {
        [Translations.NO_ACCOUNT_TEXT]: "¿No tienes cuenta aún?",
        [Translations.CREATE_ACCOUNT_TEXT]: "Crear una cuenta",
        signInHeader: "Inicie sesión en su cuenta de Fizz",
        signUpHeader: "Crea tu cuenta de fizz",
        emailLabel: "Email",
        emailPlaceHolder: "tu.email@exemple.com",
        passwordLabel: "Contraseña",
        passwordPlaceHolder: "xxxxxxxxx",
        phoneNumberLabel: "Número de teléfono",
        phoneNumberPlaceHolder: "555-555-5555",
        signUpButtonText: "REGÍSTRATE",
        signInButtonText: "REGISTRARSE",
        signInText: "Registrarse",
        haveAccountText: "¿Tener una cuenta?",
        resetYourPassword: "Restablecer su contraseña",
        sendCode: "Enviar código",
    },
    de: {
        [Translations.NO_ACCOUNT_TEXT]: "Noch keinen Account?",
        [Translations.CREATE_ACCOUNT_TEXT]: "Konto erstellen",
        signInHeader: "Melden Sie sich in Ihrem Fizz-Konto an",
        signUpHeader: "Erstellen Sie Ihr Fizz-Konto",
        emailLabel: "Email",
        emailPlaceHolder: "ihre.email@example.com",
        passwordLabel: "Passwort",
        passwordPlaceHolder: "xxxxxxxxx",
        phoneNumberLabel: "Telefonnummer",
        phoneNumberPlaceHolder: "555-555-5555",
        signUpButtonText: "ANMELDEN",
        signInButtonText: "EINLOGGEN",
        signInText: "Anmelden",
        haveAccountText: "Ein Konto haben?",
        resetYourPassword: "Setze dein Passwort zurück",
        sendCode: "Code senden",
    },
    vn: {
        [Translations.NO_ACCOUNT_TEXT]: "Chưa có tài khoản?",
        [Translations.CREATE_ACCOUNT_TEXT]: "Tạo tài khoản",
        signInHeader: "Đăng nhập tài khoản Fizz của bạn",
        signUpHeader: "Tạo tài khoản fizz của bạn",
        emailLabel: "Email",
        emailPlaceHolder: "của_bạn.email@example.com",
        passwordLabel: "mật khẩu",
        passwordPlaceHolder: "xxxxxxxxx",
        phoneNumberLabel: "Số điện thoại",
        phoneNumberPlaceHolder: "555-555-5555",
        signUpButtonText: "ĐĂNG KÝ",
        signInButtonText: "ĐĂNG NHẬP",
        signInText: "Đăng nhập",
        haveAccountText: "Có một tài khoản?",
        resetYourPassword: "Đặt lại mật khẩu của bạn",
        sendCode: "Gửi mã",
    }
};